# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(name: "Colton", email: "colton@gmail.com", password: "hellocats")
User.create(name: "Matthew", email: "matthew@gmail.com", password: "hikitty")
User.create(name: "Kathy", designer: "true".to_bool, email: "kathy@gmail.com", password: "iheartdogs")

Room.create(user_id: 1, description: "Bedroom", width: 15, depth: 102)
Room.create(user_id: 1, description: "Bathroom", width: 12, depth: 50)
Room.create(user_id: 1, description: "Living Room", width: 112, depth: 1253)
Room.create(user_id: 2, description: "Kitchen", width: 42, depth: 5)
Room.create(user_id: 2, description: "Dining Room", width: 51, depth: 23)
Room.create(user_id: 2, description: "Rec Room", width: 25, depth: 52)
Room.create(user_id: 3, description: "Library", width: 125, depth: 234)
Room.create(user_id: 3, description: "Pantry", width: 125, depth: 542)
Room.create(user_id: 3, description: "Family Room", width: 125, depth: 235)

FurnitureType.create(description: "sofa")
FurnitureType.create(description: "chair")
FurnitureType.create(description: "table")
FurnitureType.create(description: "bed")
FurnitureType.create(description: "storage")
FurnitureType.create(description: "lighting")
FurnitureType.create(description: "decor")

Furniture.create(description: "Midcentury couch", user_id: 1, price: 1.00, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 1)
Furniture.create(description: "Retro bed", user_id: 2, price: 12.23, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 4)
Furniture.create(description: "Ceramic lamp", user_id: 3, price: 123.52, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 6)
Furniture.create(description: "Leather sectional", user_id: 1, price: 1234.62, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 1)
Furniture.create(description: "Bar stools", user_id: 2, price: 54.30, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 2)
Furniture.create(description: "Toy box", user_id: 3, price: 4531.80, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 5)
Furniture.create(description: "Landscape painting", user_id: 1, price: 12345.67, quantity: 50, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 7)
Furniture.create(description: "Dining table", user_id: 2, price: 500.12, quantity: 2, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 3)
Furniture.create(description: "Nightstand", user_id: 3, price: 32.1, quantity: 93, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 3)
Furniture.create(description: "Rug", user_id: 1, price: 85, quantity: 12, width: 60.1, depth: 12.32, height: 20.0, furniture_type_id: 1)

FurniturePiece.create(room_id: 1, furniture_id: 9)
FurniturePiece.create(room_id: 1, furniture_id: 2)
FurniturePiece.create(room_id: 2, furniture_id: 2)
FurniturePiece.create(room_id: 2, furniture_id: 2)
FurniturePiece.create(room_id: 3, furniture_id: 4)
FurniturePiece.create(room_id: 3, furniture_id: 6)
FurniturePiece.create(room_id: 4, furniture_id: 7)
FurniturePiece.create(room_id: 4, furniture_id: 8)
FurniturePiece.create(room_id: 5, furniture_id: 9)
FurniturePiece.create(room_id: 5, furniture_id: 1)
FurniturePiece.create(room_id: 6, furniture_id: 3)
FurniturePiece.create(room_id: 6, furniture_id: 4)
FurniturePiece.create(room_id: 7, furniture_id: 6)
FurniturePiece.create(room_id: 8, furniture_id: 8)
FurniturePiece.create(room_id: 9, furniture_id: 1)
